eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka


server:
  port: 4444
spring:
  application:
    name: subscription
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: postgres
    password: nassim
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect