server:
  port: 8222

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id : subscription
            uri : lb://SUBSCRIPTION
            predicates:
              - Path =/subscription/**
            filters:
              - AuthenticationFilter

          - id: auth-service
            uri : lb://AUTH-SERVICE
            predicates:
              - Path =/auth/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

